// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownloadRecord(arg1) {
  return window['go']['history']['API']['AddDownloadRecord'](arg1);
}

export function ClearDownloadHistory() {
  return window['go']['history']['API']['ClearDownloadHistory']();
}

export function GetDownloadHistory() {
  return window['go']['history']['API']['GetDownloadHistory']();
}

export function GetStore() {
  return window['go']['history']['API']['GetStore']();
}
