// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibrary() {
  return window['go']['config']['API']['AddLibrary']();
}

export function GetActiveLibrary() {
  return window['go']['config']['API']['GetActiveLibrary']();
}

export function GetBandizipPath() {
  return window['go']['config']['API']['GetBandizipPath']();
}

export function GetLibraries() {
  return window['go']['config']['API']['GetLibraries']();
}

export function GetOutputDir() {
  return window['go']['config']['API']['GetOutputDir']();
}

export function GetProxy() {
  return window['go']['config']['API']['GetProxy']();
}

export function SetActiveLibrary(arg1) {
  return window['go']['config']['API']['SetActiveLibrary'](arg1);
}

export function SetBandizipPath(arg1) {
  return window['go']['config']['API']['SetBandizipPath'](arg1);
}

export function SetOutputDir() {
  return window['go']['config']['API']['SetOutputDir']();
}

export function SetProxy(arg1) {
  return window['go']['config']['API']['SetProxy'](arg1);
}
