// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibrary():Promise<boolean>;

export function GetActiveLibrary():Promise<string>;

export function GetBandizipPath():Promise<string>;

export function GetLibraries():Promise<Array<string>>;

export function GetOutputDir():Promise<string>;

export function GetProxy():Promise<string>;

export function SetActiveLibrary(arg1:string):Promise<boolean>;

export function SetBandizipPath(arg1:string):Promise<boolean>;

export function SetOutputDir():Promise<boolean>;

export function SetProxy(arg1:string):Promise<boolean>;
