// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';
import {dto} from '../models';
import {context} from '../models';

export function CancelCrawl(arg1:string):Promise<boolean>;

export function ClearHistory():Promise<void>;

export function GetActiveTasks():Promise<Array<task.DownloadTask>>;

export function GetAllTasks():Promise<Array<task.DownloadTask>>;

export function GetHistoryTasks():Promise<Array<dto.DownloadTaskDTO>>;

export function GetTaskByID(arg1:string):Promise<task.DownloadTask>;

export function GetTaskProgress(arg1:string):Promise<Record<string, any>>;

export function Lock():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartCrawl(arg1:string):Promise<string>;

export function TryLock():Promise<boolean>;

export function Unlock():Promise<void>;
