// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCrawl(arg1) {
  return window['go']['api']['CrawlerAPI']['CancelCrawl'](arg1);
}

export function ClearHistory() {
  return window['go']['api']['CrawlerAPI']['ClearHistory']();
}

export function GetActiveTasks() {
  return window['go']['api']['CrawlerAPI']['GetActiveTasks']();
}

export function GetAllTasks() {
  return window['go']['api']['CrawlerAPI']['GetAllTasks']();
}

export function GetHistoryTasks() {
  return window['go']['api']['CrawlerAPI']['GetHistoryTasks']();
}

export function GetTaskByID(arg1) {
  return window['go']['api']['CrawlerAPI']['GetTaskByID'](arg1);
}

export function GetTaskProgress(arg1) {
  return window['go']['api']['CrawlerAPI']['GetTaskProgress'](arg1);
}

export function Lock() {
  return window['go']['api']['CrawlerAPI']['Lock']();
}

export function SetContext(arg1) {
  return window['go']['api']['CrawlerAPI']['SetContext'](arg1);
}

export function StartCrawl(arg1) {
  return window['go']['api']['CrawlerAPI']['StartCrawl'](arg1);
}

export function TryLock() {
  return window['go']['api']['CrawlerAPI']['TryLock']();
}

export function Unlock() {
  return window['go']['api']['CrawlerAPI']['Unlock']();
}
