// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectBandizipPath() {
  return window['go']['archive']['API']['DetectBandizipPath']();
}

export function ExtractArchive(arg1) {
  return window['go']['archive']['API']['ExtractArchive'](arg1);
}

export function ExtractPendingArchives() {
  return window['go']['archive']['API']['ExtractPendingArchives']();
}

export function ScanArchives() {
  return window['go']['archive']['API']['ScanArchives']();
}
