// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ArchiveItem {
  archivePath: string;
  archiveName: string;
  libraryPath: string;
  targetDir: string;
  status: string;
  reason: string;
  sizeBytes: number;
}

export interface ScanResult {
  roots: Array<string>;
  activeLibrary: string;
  bandizipPath: string;
  totalCount: number;
  pendingCount: number;
  extractedCount: number;
  failedCount: number;
  items: Array<ArchiveItem>;
}

export interface ExtractActionResult {
  archivePath: string;
  archiveName: string;
  targetDir: string;
  status: string;
  message: string;
}

export interface ExtractSummary {
  bandizipPath: string;
  totalCount: number;
  extractedCount: number;
  skippedCount: number;
  failedCount: number;
  results: Array<ExtractActionResult>;
}

export function DetectBandizipPath(): Promise<string>;

export function ExtractArchive(arg1: string): Promise<ExtractActionResult>;

export function ExtractPendingArchives(): Promise<ExtractSummary>;

export function ScanArchives(): Promise<ScanResult>;
