param(
  [string]$RepoIndexUrl = 'https://miru-repo.0n0.dev/index.json',
  [string]$RepoBaseUrl = 'https://miru-repo.0n0.dev',
  [string]$OutputDir = (Join-Path $PSScriptRoot '..\sources\miru')
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

function Convert-ToSafeFileName {
  param([string]$Value)

  $safe = ($Value -replace '[^a-zA-Z0-9._-]', '-').Trim('-')
  if ([string]::IsNullOrWhiteSpace($safe)) {
    return 'source'
  }

  return $safe.ToLowerInvariant()
}

function Convert-ToSourceId {
  param([string]$Package)

  $normalized = ($Package -replace '[^a-zA-Z0-9]+', '-').Trim('-').ToLowerInvariant()
  if ([string]::IsNullOrWhiteSpace($normalized)) {
    return 'miru-source'
  }

  return "miru-$normalized"
}

function Convert-ToNullableBool {
  param($Value)

  if ($null -eq $Value) {
    return $null
  }

  $text = [string]$Value
  if ([string]::IsNullOrWhiteSpace($text)) {
    return $null
  }

  switch ($text.Trim().ToLowerInvariant()) {
    'true' { return $true }
    'false' { return $false }
    default { return $null }
  }
}

$adapterHints = @{
  'baozimh.com' = 'baozi'
  'mangadex.org' = 'mangadex'
}

$repoIndex = Invoke-RestMethod -Uri $RepoIndexUrl
$mangaSources = @($repoIndex | Where-Object { $_.type -eq 'manga' } | Sort-Object name, package)

$resolvedOutputDir = [System.IO.Path]::GetFullPath($OutputDir)
if (-not (Test-Path $resolvedOutputDir)) {
  New-Item -ItemType Directory -Path $resolvedOutputDir -Force | Out-Null
}

$generatedFiles = New-Object System.Collections.Generic.List[string]
$usedFileNames = @{}
$importedAt = (Get-Date).ToString('s')

foreach ($entry in $mangaSources) {
  $package = [string]$entry.package
  $fileStem = Convert-ToSafeFileName -Value $package
  if ($usedFileNames.ContainsKey($fileStem)) {
    $fileStem = Convert-ToSafeFileName -Value ([string]$entry.url -replace '\.js$', '')
  }
  if ($usedFileNames.ContainsKey($fileStem)) {
    $fileStem = "{0}-{1}" -f $fileStem, (Convert-ToSafeFileName -Value ([string]$entry.name))
  }
  $usedFileNames[$fileStem] = $true
  $targetPath = Join-Path $resolvedOutputDir "$fileStem.json"

  $manifest = [ordered]@{
    id           = Convert-ToSourceId -Package $package
    adapter      = $adapterHints[$package]
    provider     = 'miru'
    engine       = 'catalog'
    enabled      = $false
    builtIn      = $false
    name         = [string]$entry.name
    type         = 'manga'
    language     = [string]$entry.lang
    website      = [string]$entry.webSite
    version      = [string]$entry.version
    package      = $package
    author       = [string]$entry.author
    license      = [string]$entry.license
    icon         = [string]$entry.icon
    nsfw         = Convert-ToNullableBool -Value $entry.nsfw
    capabilities = @('search', 'detail', 'read')
    description  = if ($adapterHints.ContainsKey($package)) {
      "Imported from Miru manga catalog. This manifest already points at the current ImageMaster adapter hint '$($adapterHints[$package])', but stays disabled until you explicitly enable it."
    } else {
      'Imported from Miru manga catalog. This is catalog metadata only for now; ImageMaster adapter/runtime wiring still needs to be implemented before it can be enabled.'
    }
    upstream     = 'miru'
    upstreamUrl  = $RepoIndexUrl
    scriptUrl    = "$RepoBaseUrl/repo/$([string]$entry.url)"
    importedAt   = $importedAt
    notes        = 'Generated by scripts/import_miru_manga_sources.ps1'
  }

  $manifestJson = $manifest | ConvertTo-Json -Depth 10
  Set-Content -Path $targetPath -Value $manifestJson -Encoding UTF8
  $generatedFiles.Add((Split-Path -Leaf $targetPath))
}

$localIndex = [ordered]@{
  version = '0.1.0'
  source  = 'miru-manga-catalog'
  count   = $generatedFiles.Count
  sources = $generatedFiles
}
$localIndex | ConvertTo-Json -Depth 5 | Set-Content -Path (Join-Path $resolvedOutputDir 'index.json') -Encoding UTF8

$readme = @"
# Miru Manga Catalog Mirror

This folder is a local mirror of the `manga` entries from `miru-repo.0n0.dev`.

- These manifests are **catalog metadata first**
- They are **disabled by default**
- They preserve Miru package/script/origin info so ImageMaster can adapt them later
- Only manifests that already have an ImageMaster adapter hint can be enabled after review

Generated from:
- $RepoIndexUrl

Generated at:
- $importedAt
"@

Set-Content -Path (Join-Path $resolvedOutputDir 'README.md') -Value $readme -Encoding UTF8

Write-Host "Imported $($generatedFiles.Count) Miru manga source manifests into $resolvedOutputDir"
