// This file is automatically generated. DO NOT EDIT

export function GetSourceDetail(arg1: string, arg2: string): Promise<any>;
export function GetSourceImages(arg1: string, arg2: string): Promise<any>;
export function ListSources(): Promise<Array<any>>;
export function SearchSources(arg1: string, arg2: string, arg3: number): Promise<any>;
