// @ts-check
// This file is automatically generated. DO NOT EDIT

export function ListSources() {
  return window['go']['source']['API']['ListSources']()
}

export function SearchSources(arg1, arg2, arg3) {
  return window['go']['source']['API']['SearchSources'](arg1, arg2, arg3)
}
